# ===================================================================
# framework specific properties
# ===================================================================

# datasource
druid:
  url: jdbc:mysql://192.168.31.244:3306/shancha_system?useUnicode=true&characterEncoding=utf8&useSSL=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: 123456
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true

