server:
  port: 1111
spring:
  application:
    name: shancha-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://git.oschina.net/zhou666/spring-cloud-7simple.git
#          search-paths: shancha-config-repo
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/

