server:
  port: 1111
spring:
  application:
    name: shancha-config-server
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: ../shancha-config-repo
        git:
          uri: https://git.oschina.net/zhou666/spring-cloud-7simple.git
          search-paths: cloud-config-repo
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/

