server:
  port: 1111
spring:
  application:
    name: shancha-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qiangw808/shancha-parent.git
          search-paths: shancha-config-repo
          username: qiangw808@gmail.com
          password: ginger810518
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/

