server:
  port: 1111
spring:
  application:
    name: shancha-conf-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qiangw808/shancha-parent.git
          search-paths: shancha-config-repo
          username: qiangw808@gmail.com
          password: ginger810518
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:8888/eureka/

