server:
  port: 8081
spring:
  application:
    name: shancha-api-gateway
zuul:
  routes:
    admin:
      path: /admin/**
#      url: http://localhost:80/
      serviceId: shancha-admin-service
      strip-prefix: false

#hystrix:
#  command:
#    shancha-admin-service:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.port:8888}/eureka/