logging:
  level:
    tk:
      mybatis: TRACE
    com:
      framework: TRACE

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  type-aliases-package: com.shancha.admin.model
  mapper-locations: classpath*:/mappers/**.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.shancha.admin.util.MyMapper
  not-empty: true
  identity: MYSQL
spring:
  http:
    multipart:
      #默认支持文件上传
      enabled: true
      #支持文件写入磁盘
      file-size-threshold: 0
      #上传文件的临时目录
      location: c:/tmp
      #最大支持文件大小
      max-file-size: 1Mb
      #最大支持请求大小
      max-request-size: 10Mb


