server:
  port: 8888
eureka:
  instance:
    hostname: localhost
    #renew频率，向Eureka服务发送renew信息，默认30秒
    lease-renewal-interval-in-seconds: 10
    #服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: shancha-eureka-server

